all: fileopen fileread filewrite marks

fileopen:
	gcc -Wall -o fileopen fileopen.c

fileread:
	gcc -Wall -o fileread fileread.c

filewrite:
	gcc -Wall -o filewrite filewrite.c

marks:
	gcc -Wall -o marks marks.c

clean:
	-rm fileopen fileread filewrite marks
